# Generated by Django 4.2.13 on 2024-05-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="users",
            name="email",
        ),
        migrations.RemoveField(
            model_name="users",
            name="expiration",
        ),
        migrations.RemoveField(
            model_name="users",
            name="g_patent",
        ),
        migrations.RemoveField(
            model_name="users",
            name="g_scholar",
        ),
        migrations.RemoveField(
            model_name="users",
            name="image",
        ),
        migrations.RemoveField(
            model_name="users",
            name="inv_code",
        ),
        migrations.RemoveField(
            model_name="users",
            name="orcid",
        ),
        migrations.RemoveField(
            model_name="users",
            name="phone",
        ),
        migrations.AddField(
            model_name="users",
            name="user_type",
            field=models.IntegerField(default=3),
        ),
    ]
