# Generated by Django 4.2.13 on 2024-06-06 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daily_evaluation", models.BooleanField(default=False)),
                ("personnel", models.BooleanField(default=False)),
                ("groups", models.BooleanField(default=False)),
                ("indicators", models.BooleanField(default=False)),
                ("substitute", models.BooleanField(default=False)),
                ("logs", models.BooleanField(default=False)),
                ("reports", models.BooleanField(default=False)),
                (
                    "pid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
