# Generated by Django 4.2.13 on 2024-05-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_users_date_of_birth_remove_users_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="user_type",
            field=models.IntegerField(),
        ),
    ]
