# Generated by Django 4.2.13 on 2024-06-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_permissions_pid"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissions",
            name="overheads",
            field=models.BooleanField(default=False),
        ),
    ]
