# Generated by Django 4.2.13 on 2024-06-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_permissions_overheads"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="user_type",
        ),
    ]
