# Generated by Django 4.2.13 on 2024-05-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IndicatorItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_id", models.CharField(max_length=25)),
                ("it_id", models.CharField(max_length=25)),
                ("item", models.CharField(max_length=25)),
                ("min_effect", models.CharField(max_length=25)),
                ("default_effect", models.CharField(max_length=25)),
                ("max_efect", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Indicators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_id", models.CharField(max_length=10)),
                ("item_type", models.CharField(max_length=250)),
            ],
        ),
    ]
