# Generated by Django 4.2.13 on 2024-05-26 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Indicators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_id", models.CharField(max_length=10)),
                ("item_type", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="", null=True)),
            ],
        ),
        migrations.CreateModel(
            name="IndicatorItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("it_id", models.CharField(max_length=25)),
                ("item", models.CharField(max_length=500)),
                ("min_effect", models.IntegerField()),
                ("default_effect", models.IntegerField()),
                ("max_effect", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True, default="", null=True)),
                (
                    "in_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicators.indicators",
                    ),
                ),
            ],
        ),
    ]
