# Generated by Django 4.2.13 on 2024-05-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicatoritems",
            name="description",
            field=models.TextField(default=3),
        ),
    ]
