# Generated by Django 4.2.13 on 2024-05-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0002_indicatoritems_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicators",
            name="description",
            field=models.TextField(default=3),
        ),
        migrations.AlterField(
            model_name="indicators",
            name="item_type",
            field=models.CharField(max_length=500),
        ),
    ]
