# Generated by Django 4.2.13 on 2024-05-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0004_remove_indicatoritems_max_efect_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatoritems",
            name="item",
            field=models.CharField(max_length=500),
        ),
    ]
