# Generated by Django 4.2.13 on 2024-05-22 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("g_code", models.CharField(max_length=10)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="IndicatorItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_id", models.CharField(max_length=25)),
                ("it_id", models.CharField(max_length=25)),
                ("item", models.CharField(max_length=25)),
                ("min_effect", models.CharField(max_length=25)),
                ("default_effect", models.CharField(max_length=25)),
                ("max_efect", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Indicators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_id", models.CharField(max_length=10)),
                ("item_type", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Overheads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_id", models.CharField(max_length=10)),
                ("overhead_level", models.CharField(max_length=10)),
                ("overhead_id", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="GroupMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("g_code", models.CharField(max_length=100)),
                ("from_date", models.CharField(max_length=10)),
                ("from_time", models.CharField(max_length=10)),
                ("to_date", models.CharField(max_length=10)),
                ("to_time", models.CharField(max_length=10)),
                (
                    "pid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assessments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pid", models.CharField(max_length=10)),
                ("occure_date", models.CharField(max_length=25)),
                ("occure_time", models.CharField(max_length=25)),
                ("in_id", models.CharField(max_length=25)),
                ("it_id", models.CharField(max_length=25)),
                ("score", models.CharField(max_length=25)),
                ("status", models.CharField(max_length=25)),
                ("record_id", models.CharField(max_length=10)),
                ("record_date", models.CharField(max_length=25)),
                ("record_time", models.CharField(max_length=50)),
                ("current", models.CharField(max_length=10)),
                ("forecastEffectTime", models.CharField(max_length=10)),
                ("realeffect_time", models.CharField(max_length=10)),
                (
                    "assessor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
