# Generated by Django 4.2.13 on 2024-05-26 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Overheads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_id", models.CharField(max_length=10)),
                ("overhead_level", models.CharField(max_length=10)),
                ("overhead_id", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Assessments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occure_date", models.CharField(max_length=25)),
                ("occure_time", models.CharField(blank=True, max_length=25, null=True)),
                ("in_id", models.CharField(max_length=25)),
                ("it_id", models.CharField(max_length=25)),
                ("score", models.IntegerField()),
                ("status", models.CharField(max_length=25)),
                ("record_id", models.CharField(max_length=10)),
                ("record_date", models.CharField(max_length=25)),
                ("record_time", models.CharField(blank=True, max_length=50, null=True)),
                ("current", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "forecastEffectTime",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "realeffect_time",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("description", models.TextField()),
                (
                    "assessor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments_as_assessor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments_as_pid",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
