# Generated by Django 4.2.13 on 2024-05-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.RemoveField(
            model_name="groupmembers",
            name="pid",
        ),
        migrations.DeleteModel(
            name="IndicatorItems",
        ),
        migrations.DeleteModel(
            name="Indicators",
        ),
        migrations.AddField(
            model_name="assessments",
            name="body",
            field=models.TextField(default="3"),
        ),
        migrations.DeleteModel(
            name="GroupMembers",
        ),
    ]
