# Generated by Django 4.2.13 on 2024-05-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_delete_group_remove_groupmembers_pid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessments",
            name="assessor_id",
            field=models.CharField(max_length=10),
        ),
    ]
