# Generated by Django 4.2.13 on 2024-05-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_assessments_assessor_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessments",
            name="body",
        ),
        migrations.AddField(
            model_name="assessments",
            name="descriptoin",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="current",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="occure_time",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="realeffect_time",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="record_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
