# Generated by Django 4.2.13 on 2024-06-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_assessments_overhead_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessments",
            name="overhead_level",
            field=models.IntegerField(default=1),
        ),
    ]
