# Generated by Django 4.2.13 on 2024-05-25 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_remove_assessments_body_assessments_descriptoin_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assessments",
            old_name="descriptoin",
            new_name="description",
        ),
    ]
