# Generated by Django 4.2.13 on 2024-05-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_rename_descriptoin_assessments_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessments",
            name="description",
            field=models.TextField(),
        ),
    ]
