# Generated by Django 4.2.13 on 2024-05-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_assessments_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessments",
            name="score",
            field=models.IntegerField(),
        ),
    ]
