# Generated by Django 4.2.13 on 2024-05-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_alter_assessments_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessments",
            name="forecastEffectTime",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
