# Generated by Django 4.2.13 on 2024-09-10 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0007_assessments_substitute_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessments",
            name="substitute_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="substitute_as_assessor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
