# Generated by Django 4.2.13 on 2024-05-26 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0008_alter_assessments_forecasteffecttime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessments",
            name="pid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
