# Generated by Django 4.2.13 on 2024-05-26 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0009_alter_assessments_pid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessments",
            name="assessor_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments_as_assessor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="assessments",
            name="pid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments_as_pid",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
