# Generated by Django 4.2.13 on 2024-07-11 00:49

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("substitute", "0003_alter_substitute_daily_evaluation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="substitute",
            name="from_time",
            field=django_jalali.db.models.jDateField(default=datetime.date(2011, 8, 3)),
        ),
        migrations.AddField(
            model_name="substitute",
            name="to_date",
            field=django_jalali.db.models.jDateField(default=datetime.date(2011, 8, 3)),
        ),
    ]
