# Generated by Django 4.2.13 on 2024-07-11 00:50

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("substitute", "0004_substitute_from_time_substitute_to_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="substitute",
            name="from_time",
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name="substitute",
            name="to_date",
            field=django_jalali.db.models.jDateField(),
        ),
    ]
