# Generated by Django 4.2.13 on 2024-07-11 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("substitute", "0005_alter_substitute_from_time_alter_substitute_to_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="substitute",
            old_name="from_time",
            new_name="from_date",
        ),
    ]
