# Generated by Django 4.2.13 on 2024-09-10 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("substitute", "0006_rename_from_time_substitute_from_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="substitute",
            name="from_time",
            field=models.CharField(
                blank=True,
                max_length=5,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Time must be in the format HH:MM",
                        regex="^([01]\\d|2[0-3]):[0-5]\\d$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="substitute",
            name="to_time",
            field=models.CharField(
                blank=True,
                max_length=5,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Time must be in the format HH:MM",
                        regex="^([01]\\d|2[0-3]):[0-5]\\d$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="substitute",
            name="from_date",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Date must be in the format YYYY-MM-DD",
                        regex="^\\d{4}-\\d{2}-\\d{2}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="substitute",
            name="to_date",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Date must be in the format YYYY-MM-DD",
                        regex="^\\d{4}-\\d{2}-\\d{2}$",
                    )
                ],
            ),
        ),
    ]
