# Generated by Django 4.2.13 on 2024-09-10 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("substitute", "0007_substitute_from_time_substitute_to_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="substitute",
            name="from_date",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Date must be in the format YYYY-MM-DD",
                        regex="^\\d{4}-\\d{2}-\\d{2}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="substitute",
            name="to_date",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Date must be in the format YYYY-MM-DD",
                        regex="^\\d{4}-\\d{2}-\\d{2}$",
                    )
                ],
            ),
        ),
    ]
