# Generated by Django 4.2.13 on 2024-06-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overheads", "0005_utils"),
    ]

    operations = [
        migrations.AlterField(
            model_name="overheads",
            name="overhead_level",
            field=models.IntegerField(),
        ),
    ]
