# Generated by Django 4.2.13 on 2024-06-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overheads", "0006_alter_overheads_overhead_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="overheads",
            name="overhead_level",
            field=models.CharField(max_length=100),
        ),
    ]
