# Generated by Django 4.2.13 on 2024-07-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overheads", "0007_alter_overheads_overhead_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="overheads",
            name="approver",
            field=models.BooleanField(default=False),
        ),
    ]
