# Generated by Django 4.2.13 on 2024-07-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groups",
            name="g_code",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
