# Generated by Django 4.2.13 on 2024-05-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Groups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("g_code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(default="")),
            ],
        ),
        migrations.AddField(
            model_name="groupmembers",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="groupmembers",
            name="g_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="groups.groups"
            ),
        ),
        migrations.DeleteModel(
            name="Group",
        ),
    ]
