# Generated by Django 4.2.13 on 2024-05-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_groups_groupmembers_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmembers",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="groups",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
