# Generated by Django 4.2.13 on 2024-05-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_alter_groupmembers_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmembers",
            name="to_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="groupmembers",
            name="to_time",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
